### ISSUE TITLE
E-Mail-Adressen case sensitive?

### ISSUE THREAD

**Issue by rahim-t** [valuehack/scholarium.at#111]
Doppeltes Account entstanden mit selber E-Mail-Adresse, nur Großschreibung des Namens. Offenbar sind E-Mail-Adresse case-sensitive, bitte ändern. Benutzer: Johannes Blum

**Comment by MerlinB** [comment]
Nicht reproduzierbar. Login und Erstellung sind nicht case-sensitiv. Ein Rätsel...
