### ISSUE TITLE
Zahlungsabwicklung

### ISSUE THREAD

**Issue by wmles** [valuehack/scholarium.at#12]
Auf der Spende-Seite sofortüberweisung/paypal einrichten

**Comment by wmles** [comment]
@MerlinB - du hattest das doch schonmal gemacht und es scheiterte nur noch am ssl-Zertifikat, oder? Letzteres ist jetzt auf dem Server eingerichtet, da dürfte auch paypal nicht mehr meckern

**Comment by MerlinB** [comment]
Bei eingeloggtem Zustand: Daten sollte vorausgefüllt sein.

**Comment by MerlinB** [comment]
- [ ] Versandkosten werden nicht mit abgezogen

**Comment by MerlinB** [comment]
- [ ] Handling von Kauf bei zu wenig Guthaben

**Comment by MerlinB** [comment]
Paypal ist jetzt als Button implementiert, da die API nicht funktioniert. Abo ist so nicht möglich, aber es funktioniert.
