### ISSUE TITLE
Accidental promotion of all users through import of old DB

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#126]
Bei dem Import der Nutzer aus der alten Datenbank und der Aktivierung der neuen Seite (26.10.17 denke ich) wurden alle Benutzer um eine Stufe hochgestuft.

Aktueller Stand:
`[1537, 19, 221, 156, 80, 37, 18, 10]`

Die 1500 "Gäste" wurden bereits auf Interessenten zurückgestuft. Alle restlichen Unterstützer sind noch potentiell eine Stufe zu hoch, so dass 10 Personen auch eine Stufe über Patron haben.
Das ist weniger kritisch als es bei den Interessenten war, da ihnen nur eine falsche Stufe angezeigt wird und sie nur per Email entsprechende Belohnungen einfordern.

Problem für alle Nutzer, die seit der Umstellung unterstützt haben:  Durch die aktuelle Implementierung der Unterstützungen (https://github.com/valuehack/scholarium.at/issues/23) kann eine höhere Stufe auch bei einer niedrigen Unterstützung beibehalten werden. Es ist im Nachhinein nur noch durch historische Bestätigungsemails an uns möglich herauszufinden, für welche Stufe bezahlt wurde. 

Wenn ich das richtig sehe sind unsere Optionen:
Für Alle Nutzer mit stufe >= 2 (Stufe 1 ist bereits niedrigste Stufe und Interessenten sind schon entfernt):
- Zurückstufen, wenn die letzte Unterstützung vor dem 26.10. stattgefunden hat (230 Nutzer):
```
for profile in ScholariumProfile.objects.filter(stufe__gte=2, letzte_zahlung__lt=date(2017,10,26)):
    profile.stufe = profile.stufe - 1
    profile.save()
```
- Alle Nutzer mit stufe = 7 zurückstufen (Stufe existiert nicht, kann aber durch Zahlung beibehalten werden).
- Alle anderen (104 Nutzer) mit Hilfe der Emails an info@scholarium.at einordnen und ihnen im Zweifelsfall die höhere Stufe zu lassen.

**Comment by MerlinB** [comment]
Für eine Liste der 105 betroffenen Nutzer: 
```
for obj in ScholariumProfile.objects.filter(stufe__range=['1','6'], letzte_zahlung__gte=date(2017,10,26)):
     row = []
     for field in ['first_name', 'last_name', 'email']:
         val = getattr(getattr(obj, 'user'), field)
         row.append(val)
     for field in ['firma', 'letzte_zahlung']:
         val = getattr(obj, field)
         row.append(val)
     row.append(ScholariumProfile.stufe_choices[obj.stufe])
     writer.writerow(row)
```

**Comment by MerlinB** [comment]
@wmles Habe ich etwas übersehen, oder würdest du dem so zustimmen?

**Comment by MerlinB** [comment]
Neues Problem: Es gibt wohl Nutzer, deren `letzte_zahlung` nicht geupdated wurde. Wie kann das passieren?

**Comment by wmles** [comment]
Hallo Merlin, 

ich verstehe nicht, was du mit dem writer.writerow() machst :). Und ich verstehe auch nciht, wie du auf 105 kommst, ich habe 111 Nutzer, die in der Zwischenzeit gezahlt haben.

ich hätte mal die Stufen mit den Stufen aus der alten DB verglichen:

> import sqlite3 as lite
import datetime
from Grundgeruest.models import ScholariumProfile

con = lite.connect('/home/scholarium/alte_db.sqlite3')
with con:
    con.row_factory = lite.Row
    cur = con.cursor()
    cur.execute("SELECT * FROM mitgliederExt")
    mitglieder = [dict(zeile) for zeile in cur.fetchall()]

pks = [pro.alt_id for pro in ScholariumProfile.objects.filter(alt_id__gt=0)]
stufen_alt = {mit['user_id']: mit['Mitgliedschaft'] for mit in mitglieder if mit['user_id'] in pks}
stichtag = datetime.date(2018, 10, 26)

unterstuetzer_importiert = ScholariumProfile.objects.filter(alt_id__gt=0).filter(stufe__gt=0)
profile_schongezahlt = {pr.alt_id: pr for pr in unterstuetzer_importiert.filter(datum_ablauf__gt=stichtag)}
profile_nochnicht = {pr.alt_id: pr for pr in unterstuetzer_importiert.filter(datum_ablauf__lte=stichtag)}

stufengleich_nochnicht = {pk: (pr.stufe==stufen_alt[pk]) for pk, pr in profile_nochnicht.items()}
stufengleich_schongezahlt = {pk: (pr.stufe==stufen_alt[pk]) for pk, pr in profile_schongezahlt.items()}

print('Von %s Nutzern, die schon gezahlt haben, weichen bei folgenden Profil-ids die Stufen von den Stufen der alten db ab: %s' % (len(stufengleich_schongezahlt), [pk for pk, ob in stufengleich_schongezahlt.items() if not ob]))
print('Von %s Nutzern, die noch nicht gezahlt haben, weichen bei folgenden Profil-ids die Stufen von den Stufen der alten db ab: %s' % (len(stufengleich_nochnicht), [pk for pk, ob in stufengleich_nochnicht.items() if not ob]))

**Comment by wmles** [comment]
dann könnte man die "sicheren" anpassen mit:

for pk, pro in [(pk, pro) for pk, pro in profile_nochnicht.items() if stufengleich_nochnicht[pk]]:
    pro.stufe += -1 
    pro.save()

**Comment by wmles** [comment]
Ich habe jetzt mal von den 413 Nutzern, die 411, die seit der Umstellung nicht gezahlt haben, und die gleiche Stufe wie vor der Umstellung hatten, um eins runtergestuft. 
Die anderen beiden sind greger@gp.co.at und mail@martinmuehlbauer.de

**Comment by MerlinB** [comment]
Wie kommst du auf 400? Ich dachte, du hast alle Gäste, die eignetlich Interessenten waren schon zurück gestuft?

**Comment by MerlinB** [comment]
Ich habe übrigens alle unklaren Nutzer (Stufe >= 2, hat gezahlt) einordnen können, ist nur noch nicht umgesetzt.

**Comment by MerlinB** [comment]
Ah, ich verstehe. Ich hatte Nutzer mit `letzte_zahlung=None` vergessen.
Allerdings haben wir immernoch eine Differenz von 23 Personen, die seitdem nciht gezahlt haben. Ich komme auf 436, du auf 413. Benutzt du `datum_ablauf` zum berechnen?

**Comment by MerlinB** [comment]
Ach, ich schätze die Differenz sind Nutzer, die seitdem nicht gezahlt haben aber trotzen eine andere Stufe haben. Kann das sein? Wie kann es dazu kommen?

**Comment by MerlinB** [comment]
Alle Nutzer, die seitdem bezahlt haben haben jetzt die richige Stufe.
