### ISSUE TITLE
Profilansicht

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#13]
- [x] Menuleiste ist leer.
- [x] Link zu "Unterstützung erneuern" funktioniert nicht.

**Comment by wmles** [comment]
hm, hast du Lust, dich mal mit context processors zu beschäftigen? :)
da müsste man einen hinzufügen, der die liste_menue aus Grundgeruest.views zurückgibt. Wenn nicht, mach ich das später mal bei Gelegenheit :)
