### ISSUE TITLE
__str__ kaputt für zahlreiche Käufe

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#131]
`__str__` Funktion kaputt (Wahrscheinlich meistens wegen `nutzer=None`). Ich schreib die Liste ins Slack.

**Comment by MerlinB** [comment]
Korrentur: Nur ein paar Käufe haben `nutzer=None`. Das Problem führt auch dazu, dass entsprechende Produkte nicht mehr gespeichert werden können!

**Comment by MerlinB** [comment]
Alle Käufe ohne Nutzer sind importiert, ich denke die paar kann man gefahrlos löschen.

**Comment by MerlinB** [comment]
Im Kauf Model unter Nutzer ist `null=True`. Wieso?

**Comment by wmles** [comment]
Habe die alle durchgeguckt, da ist nicht __str__() kaputt, sondern objekt_ausgeben() (...das von str aufgerufen wird) - also die entsprechende Ware ist nicht da. 

Das ist schwer zu verhindern, weil es auf Datenbankebene keine Verknüpfung gibt. Ich würde vorschlagen, in's objekt_ausgeben() ein try reinzumachen, und falls es das Ding nicht gibt, None oder so zurückgibt.

Es könnte sein, dass ich mir was dabei überlegt hatte, dass beim nutzer null=True ist, vielleicht damit der Kauf erhalten bleibt, auch wenn der Nutzer gelöscht wurde (dass man hinterher sehen kann wie oft das Objekt gekauft wurde, in der alten db war da irgendwann früher mal ein Feld, das das gezählt hat, glaub ich)
Das verursacht aber nie einen Fehler, steht halt einfach None statt dem Nutzer.

**Comment by wmles** [comment]
"Das Problem führt auch dazu, dass entsprechende Produkte nicht mehr gespeichert werden können!"
was meinst du damit, das habe ich nicht verstanden...

**Comment by MerlinB** [comment]
Okay, verstehe. Ich meine, dass save() der Objekte die __str__ Funktion
auruft, und deswegen nicht geht.

LG
