### ISSUE TITLE
Seminare

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#14]
Werden in /veranstaltungen angezeigt, in /seminare nicht.

**Comment by wmles** [comment]
nee, das liegt daran, dass die vergangen sind (und ich /veranstaltungen nicht gepflegt habe, und das dort deswegen nicht geprüft wird). Die vergangenen werden nur angezeigt, wenn es zu ihnen ein Medium gibt. Kann man sich streiten, ob das gut ist, aber das ist der Grund.

**Comment by wmles** [comment]
PS: ich seh in beidem was - guckst du auf localhost und hast eine unvollständige db?

**Comment by MerlinB** [comment]
Achso. Stimmt, dann passt es. 
Was ist mit dem Vorträge-Tab, der ins leere führt?
