### ISSUE TITLE
Userena Probleme: Alte Accounts

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#15]
- [ ]  Bei Eingabe einer alten, vorhandenen Email gibts die Meldung: "This email is already in use **but not confirmed**"

**Comment by wmles** [comment]
aaah, Mist :) das liegt wohl daran, dass es kein UserenaSignup-objekt für die importierten alten Datensätze gibt; wär schon elegant, wenn das nicht passiert, muss ich wohl also nochmal die import-Funktion umschreiben...

**Comment by MerlinB** [comment]
muss ausprobiert werden.
