### ISSUE TITLE
Medien

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#16]
Muss noch ganz neu implementiert werden?

**Comment by wmles** [comment]
Nenee, ist schon ziemlich fertig. Die neue url-Struktur sollte ja keinen Medien-Tab haben, die sind unter den Salons und Seminaren zu sehen. Die models für die beiden haben ja ein paar Felder, die die Datei der Aufzeichnung speichern und den ob_aktiv-Status angeben. Wenn die Dateien einmal auf dem Server sind (ich komme auf den alten nicht per ftp oder ssh drauf), und alles auf aktiv gesetzt, dann sollten die automatisch mit auftauchen - oben die kommenden Veranstaltungen, unter dem Separator die Medien der vergangenen.

**Comment by MerlinB** [comment]
Achsoo. Du musst über sftp statt ftp zugreifen.
