### ISSUE TITLE
Anmeldung/Registrierung

### ISSUE THREAD

**Issue by wmles** [valuehack/scholarium.at#2]
Für eine Methode für signin/signup entscheiden: 

 - die alte Version über modal-windows die sich öffnen
 - Links zu den eingebauten userena-urls 

und diese produktionsfertig aufhübschen.

**Comment by wmles** [comment]
Vorteile der ersten Variante: 
status quo; wird evtl als hübscher empfunden; es ist unmittelbarer deutlich, dass man auf der Seite bleibt, von der man kam.

Vorteile der zweiten Variante: 
ist schon umgesetzt; verweist auch schon auf die Seite, auf der man war; nutzt die userena-Funktionalitäten, keine Verifizierung vom Passwort per Hand, das ganze Drumrum mit Bestätigungsmails schon eingebaut; braucht kein javascript; ich weiß nicht, warum die modals falsch aussehen, habe eigentlich alles kopiert.

**Comment by MerlinB** [comment]
Die Modals verhalten sich jetzt wie vorher, aber ich habe es nicht geschafft, die usarena-forms darauf zu übertragen.

**Comment by MerlinB** [comment]
Super, damit hat sich ja alles erledigt, nicht?

**Comment by MerlinB** [comment]
Noch etwas: Bei falschen Anmeldedaten wird man auf die userena-eigene Loginseite weitergeleitet, statt nur eine Meldung zu bekommen.

**Comment by wmles** [comment]
Naja, es gab schon Gründe, dass ich gegen diese Methode mit den modals war (auch wenn mir die Gründe nicht alle bewusst waren...)
Dann schlag doch mal was besseres vor :) also konkret: wie kriegst du den user authentifiziert (also die credentials mit der Datenbank abgeglichen) ohne einen POST-request zu schicken; bzw. alternativ: wie soll eine beliebige url (denn das modal-Ding soll ja gerade von überall aufrufbar sein) den POST-request empfangen? Soll jeder view nach keywords mit den Namen user und password in den POST-daten prüfen? Klingt nicht sauber (mal ganz davon abgesehen, dass es nicht trivial zu implementieren ist), wird schon einen Grund haben, dass es nicht üblich ist, auch wenn ich wiederum nicht sagen kann, welcher Grund.

Kurz gesagt, ich wär' dafür es so zu lassen, und die userena-signin-Seite auf scholarium-Formular-Stil umzuändern damit's nicht in's Auge sticht...

**Comment by MerlinB** [comment]
Das meiste sollte jetzt richtig aussehen. 
Wenn ich meine Emailaddresse unter /nutzer/activate/... bestätigen möchte bekommen ich: ERR_CONNECTION_REFUSED. Der Server gibt keinen Fehler aus. Idee?

**Comment by MerlinB** [comment]
Wenn ich mich trotzdem anmelden möchte bekomme ich:
"Ihr Account scheint deaktiviert worden zu sein.
Falls Sie sich ungerecht behandelt fühlen, kontaktieren Sie bitte die Administratoren für die weitere Klärung."

**Comment by wmles** [comment]
Hallo Merlin,

letzteres ist schonmal gut, denn wenn die Aktivierung fehlschlägt,
sollte der account deaktiviert bleiben, das ist ja der Sinn davon :)
anscheinend bist du bitbart@protonmail, dann ist an dich eine Mail
rausgegangen. Allerdings mit localhost im Link. Wenn du das durch
wien.piokg.de ersetzt hättest, hätte es klappen müssen.

Und der Link war falsch, weil auf dem Server mysteriöserweise die
local_settings verschwunden sind. Ich bin schon der Meinung, dass die
mal da waren, stehen ja auch im .gitignore. Habe das jetzt wieder
umgestellt, also dass apache auf die local_wsgi verweist, und die die
local_settings nutzt. Hoffe, jetzt sollte es klappen.

Bis später (eigentlich ist ja schon spät genug ;))
ilja

**Comment by wmles** [comment]
PS:
hab's ausprobiert, Registrierung funktioniert.
Aber "Ihr Unterstützer-Zugang läuft noch bis zum None" ist nicht so
super :) da muss wohl noch eine if-Abfrage rein, welche Stufe man ist,
und sonst ein anderer Text rein.

**Comment by MerlinB** [comment]
Ich bekomme wieder einen localhost-Link über wien.piokg.de.

**Comment by wmles** [comment]
Verdammt :) sorry, ich hab's gestern doch nur oberflächlich geprüft :(
jetzt steht site_id = 3 drin, und jetzt kriege ich den richtigen Link
Dass profile-view closed ist, ist grade jetzt verfrüht, wie gestern im
PS geschrieben; aber mach' ich gleich mal schnell, dann ist es zurecht
closed.
