### ISSUE TITLE
Vortragsaufzeichnungen

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#20]

**Comment by wmles** [comment]
Hallo Merlin, 
den Import mache ich gerade; es gibt aber noch mehr unklare Produkte in der alten DB. Unter type gibt es folgende Einträge:
'programm', 'salon', 'privatseminar', 'vortrag', 'media-vortrag', 'antiquariat', 'buch', 'media-salon', 'projekt', 'scholie', 'video', 'media-vorlesung', 'analyse', 'seminar'

Frag doch mal Rahim (oder denk auch selber drüber nach was du meinst) was aus den Typen [buch, video, analyse, programm, privatseminar, projekt] werden soll? Buch und analyse zusammen mit antiquariat ins model Buch? projekt und privatseminar weglassen? video gibts nur eins, kommt zu Vortrag; und programm?

**Comment by MerlinB** [comment]
Heißen in der Bestellübersicht "Scholienbüchlein"

**Comment by MerlinB** [comment]
- [ ] Formatierung

**Comment by MerlinB** [comment]
- [ ] Nicht vorhandene Aufzeichnungen nicht anbieten
