### ISSUE TITLE
Reverse for salons, seminare broken

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#37]
No reverse match
```
url_slug = self.art_veranstaltung.slug
return reverse('Veranstaltungen:%s_detail' % url_slug, kwargs={'slug': self.slug})
```

**Comment by wmles** [comment]
Ist umgangen, indem die urls der detail-views halb-hargecoded werden, also der Anfang /salon/ bzw /seminar/ bzw. /vortrag/ in der get_absolute_url-methode hart drinstehen, und in den urls.py auch - also an zwei Stellen nur, ist ziemlich DRY, nur ein ganz klein wenig beschlagen :)
