### ISSUE TITLE
Profilansicht

### ISSUE THREAD

**Issue by wmles** [valuehack/scholarium.at#4]
Aufhübschen.
Einiges (Guthaben, Stufe, etc.) auf editable=False setzen. 
Wie früher Ablaufdatum etc anzeigen, Buttons zum Unterstützen.

**Comment by wmles** [comment]
Ich habe jetzt userena so angepasst, dass alle zu verändernden Daten im Projekt sind (in templates/userena und die Grundgeruest/forms.py)

**Comment by wmles** [comment]
@MerlinB - bitte kurz prüfen, und wenn die Ansicht vom Profil und das Ändern der Daten klappt, dann issue schließen

**Comment by MerlinB** [comment]
Passt alles, bis auf Link zur Spende. Besser wäre allerdings noch eine einfache Meldung nach Änderung des Passworts anstatt der Weiterleitung auf eine neue Seite mit der Bestätigung.
