### ISSUE TITLE
Rahim Admin Login: Nur über Seite möglich

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#40]

**Comment by wmles** [comment]
verstehe ich nicht, wie sollte es noch möglich sein?

**Comment by MerlinB** [comment]
Wenn ich ihn richtig verstanden habe, geht der Login nur über scholarium.at, nicht scholarium.at/admin.
Danach funktioniert der Zugriff aber.

**Comment by wmles** [comment]
okay, verstehe. Hab's probiert, ich kann mich auch nicht mit der email bei /admin/ anmelden, man braucht anscheinend den Nutzernamen (unter /nutzer/anmelden/ geht beides, und im modal nur die Mail :)). Ich ändere ihn mal zu username "rahim"
