### ISSUE TITLE
Recordings "Salon": wrong date and ordered wrongly

### ISSUE THREAD

**Issue by bogensberger** [valuehack/scholarium.at#42]
The list which contains the available recordings contains a wrong date. I assume it's the date when the file was uploaded to the server and not when the event actually happened. This leads to a wrong ordering of the events and recent events are on the last pages while quite old events are on the first page.

https://scholarium.at/salons/?seite=2

<img width="1458" alt="screen shot 2017-10-30 at 12 00 44" src="https://user-images.githubusercontent.com/1038966/32168016-34854a8a-bd6b-11e7-80a2-7f1b0b140ed1.png">

There are even events with the odd date `01. January 1111` on the last pages. Next to these events i can see the "Livestream buchen" button, even if they are clearly in the past.

<img width="1499" alt="screen shot 2017-10-30 at 12 09 26" src="https://user-images.githubusercontent.com/1038966/32168116-92f7ce94-bd6b-11e7-8056-38ab0101b734.png">

**Comment by bogensberger** [comment]
There is the same problem with the lectures (https://scholarium.at/vortrag/?seite=4). Here the order matters even more imo.

**Comment by wmles** [comment]
Vielen Dank, Herr Bogensberger, 

(übrigens auch für die früheren Hinweise im Verlauf der Entwicklung; ich bin noch nicht so sicher, ob das ein Beispiel für einen erfolgreichen rewrite from mehr-oder-weniger-scratch geworden ist) :)

Wir haben die neue Seite mit ein paar Lücken in Betrieb genommen, da auch einiges besser ist als bei der alten, und da das sonst noch ewig so weiter gehen kann, an beiden Versionen neue Sachen parallel umzusetzen. 

Das mit dem Datum der Salons ist mir sonderbarerweise durchgerutscht, hab ich jetzt nachträglich aus der alten DB importiert. Daten der Vorträge gab's da keine, die hab ich auf das Datum des ersten Kaufes des Objektes gesetzt (als einzig sinnvolle Schätzung)

Der Button "Livestream buchen" ist ein Beschriftungsproblem - er ist halt nicht live, aber man kann sich das youtube-Video ansehen. Perspektivisch soll man im Nachhinein den Link und die Aufzeichnung zusammen im Paket bekommen, das ist noch in Arbeit.

**Comment by wmles** [comment]
Das Livestream-Problem ist auch gelöst; ging dann doch einfacher als befürchtet:

man kann hinterher keinen livestream kaufen, aber wenn man eine Aufzeichnung kauft, wird auch der livestream angezeigt.
Damit ist wohl alles erledigt hier, haha! :)
