### ISSUE TITLE
Mitarbeiter-Tools

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#43]
**Offene Frage: Admin Panel als Interface für Mitarbeiter oder relevante Tools als Forms implementieren**
--------------------
- Nutzerprofile (Insb. Guthabenkontrolle)
- Produkte
- Seminare, Salons
- Newsletter generieren und abschicken (https://github.com/valuehack/scholarium.at/issues/50)

**Comment by MerlinB** [comment]
Insbesondere sollte es ein zugängliches Panel für die Scholariumprofile/Nutzer geben.

**Comment by wmles** [comment]
bitte konkretisieren und aufteilen ...
