### ISSUE TITLE
Nachrichten an info@scholarium.at

### ISSUE THREAD

**Issue by rahim-t** [valuehack/scholarium.at#54]
- Nachricht nach Unterstützungsauswahl "vielen Dank für Ihr Interesse!" nicht an uns senden
- in dieser Nachricht, sofern sie an die Unterstützer geht, stehen keine Zahlungsanweisungen - in anderem E-Mail? Sonst steht in der Nachricht gar nichts.
- in Nachricht "Nutzer hat gezahlt" steht statt username offenbar das Passwort

**Comment by wmles** [comment]
also den 3. Punkt kann ich schonmal einfach beantworten :) doch, ist der Nutzername; zugegebenermaßen ist der da nicht sooo nützlich, da man den Nutzer genauso eindeutig über die Mailadresse findet.
Das andere hätte ich gern erst auf staging ausprobiert ... aber da wird mir ein unverständlicher 500-Fehler gezeigt, @MerlinB, weißt du wo das her kommt? Was hat das mit den verschiedenen virtualenvironments auf sich und so.

**Comment by wmles** [comment]
und zu den anderen Punkten:

2. da stand bei der Zahlungsmethode Überweisung was, bei den anderen nicht; jetzt gibt's bei Bar nochmal den gleichen Text wie auf der Seite (das mit den Edelmetallen^^), und bei PayPal nur Dank, dass die Zahlung angekommen ist. 
1. ist geändert
