### ISSUE TITLE
local_settings, auch mit Django-Server

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#58]
**local_settings** sollten auch standartmäßig lokal verwendet werden, wenn sie existieren. @wmles Warum nicht statt wsgi-Verweis auf local_settings und dort `from .settings import *` am Ende von settings.py? 
```
try:
  from .local_settings import *
```

**Comment by wmles** [comment]
ja, meinetwegen, kann man machen.
ich fand das am überzeugendsten:
https://stackoverflow.com/a/14545196/6053327
aber hat beides Vor/Nachteile. Also mach ruhig andersrum.

**Comment by wmles** [comment]
... solange du nicht die staging-Umgebung und den runserver kaputt machst :-D

**Comment by MerlinB** [comment]
Ja, ich finds generell so schon besser, wie es ist. Aber hast du eine Idee, um zu umgehen, jedesmal --settings=seite.local_settings einzugeben?

**Comment by wmles** [comment]
reverse search in der bash ;)
also Strg-r, dann run

oder an .bashrc die Zeile anhängen:
alias start_srv="cd /pfad/zu/ordner; . venv/bin/activate; ./manage.py etc"
dann start_srv nutzen :)

**Comment by MerlinB** [comment]
Ja gut, das soll wohl reichen
