### ISSUE TITLE
Datenbank

### ISSUE THREAD

**Issue by wmles** [valuehack/scholarium.at#6]
Entscheiden, ob auf MySql umstellen oder so lassen.
Vorteil wäre, dass sie flexibler ist, man einfacher eine mysql-myadmin-Oberfläche dazu aktivieren kann um sie abseits der Seite zu bearbeiten, und vermutlich auch backupen einfacher ist (nicht die ganze Datei, sondern nur Änderungen).
Es funktioniert andererseits erstmal mit sqlite, wäre also wieder eine potentielle Störquelle, das anzufassen. 
Vermutlich: irgendwann später wär's nicht schlecht, ist aber nicht prioritär.

**Comment by MerlinB** [comment]
so lassen.
