### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#63]
Mehr mit Forks und Branches arbeiten?
Aktuell müssen beim Pushen in die Production-Umgebung immer alle neuen Änderungen übernommen werden, was ungünstig ist, wenn es eine kleine, einfache oder wichige Änderung gibt.

**Comment by geraldk1** [comment]
Ich habe mir drei Workflows angesehen:
- A: http://nvie.com/posts/a-successful-git-branching-model/
  - zwei main branches: *master* (production) und *develop*
  - plus *feature branches*, die von *develop* stammen und dort wieder gemergt werden
  - grundsätzlich releasebezogen
  - *hotfixes* nach Testen sofort in *master*

- B: http://scottchacon.com/2011/08/31/github-flow.html
  - ein *master*-branch (produktionsfertig) und viele *feature branches*, die nach dem Testen und häufig in *master* gemergt werden
  - *hotfixes* werden wie *normale* Features behandelt, da Deploys sowieso häufig sind
- C: http://guides.beanstalkapp.com/deployments/best-practices.html
  - drei *Environments*: Development (local), Staging, Production
  - ähnlich wie A

---

Ich tendiere zu einer Lösung ähnlich wie B, da für uns Releases keine Rolle spielen. Ein Problem, das ich sehe, könnte sein, dass man sich in der Staging Area in die Quere kommt, da man dort zum Testen in den jeweiligen Feature-Branch auschecken müsste. Hier müsste man sich abstimmen (oder es gibt eine andere Lösung?) Grundsätzlich sollte aber ohnehin zeitnah getestet und in *master* gemergt werden.

Es gäbe dann einen *master*-Branch, von dem alle anderen Branches ausgehen und der immer den aktuellen Stand in Production darstellt. Der Workflow, um ein Feature zu implementieren, sähe wie folgt aus:

1. Forken bzw. Pullen des aktuellen *master*
2. Checkout zu *feature*-Branch in local repo
3. Regelmäßiges Pushen des *feature*-Branches auf den entsprechenden *feature*-Branch im remote repo (valuehack) -> so sieht man anhand der gerade bestehenden Branches, woran gearbeitet wird.
4. Bei Fragen oder, wenn der Branch bereit zum Mergen ist, Pull Request erstellen und den *feature*-Branch reviewen lassen. (Die Pull-Request-Oberfläche kann zur Kommunikation genutzt werden.) Hier können auch Commits zur Übersichtlichkeit der Commit-Historie gesquasht werden.
5. Bei erfolgreichem Review: Merge in *master* und Deployment in Production
6. Nach Merge: Löschen des *feature*-branches lokal und remote

In Notfällen kann natürlich auf das Reviewen verzichtet werden. Ein entscheidender Vorteil im Vergleich zur jetzigen Lösung ist, dass es einen *master*-Branch gibt und damit der Stand in Production klar wird. Lösungen A oder C von oben haben noch einen anderen Hauptbranch zur Entwicklung/Staging, der aber - denke ich - nicht nötig ist, wenn es häufige Deploys gibt, und gar verwirren könnte, da der Branch in Production dann immer hinterher hängt, und man ihn regelmäßig mit dem Entwicklungsbranch mergen müsste. Ganz sicher bin ich mir dabei allerdings nicht.
