### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#68]
Wir müssen einen besseren Weg finden als den restlichen Text in die Kommentare zu schreiben. Alternativ sollte das Kommentar irgendwie markiert werden, zum Beispiel durch ein Symbol am Anfang, allerdings ist das mehr Aufwand, da Kommentare nicht ausgelesen werden können. (https://github.com/valuehack/scholarium.at/issues/69).

**Comment by rahim-t** [comment]
Eigentlich ist Trello zu ersetzen. Die einfachste Alternative ist wohl, eine Eingabemaske für Markdown-Text zu erstellen, der dann in HTML umgewandelt wird. Für die Trennung in öffentlich und privat wären eigene Tags sinnvoll (anstelle von zwei Eingabefeldern), sodass einzelne Passagen maskiert werden können.

**Comment by wmles** [comment]
auf den ersten Blick nicht trivial, aber stimmt, geht: es würde in der DB dann der volle Text und der gekürzte Text stehen; die Tags gibt's im Input, in die DB kommen nur die Endergebnisse.

**Comment by rahim-t** [comment]
Umlaute erzeugen Fehler:

Request Method: | POST
-- | --
http://127.0.0.1:3024/admin/Scholien/markdownartikel/add/
1.11.6
UnicodeDecodeError
'ascii' codec can't decode byte 0xc3 in position 109: ordinal not in range(128)
/usr/lib/python3.6/urllib/parse.py in <genexpr>, line 107
/usr/bin/python3
3.6.3
['',  '/home/scholarium/scholarium_production',  '/home/scholarium/scholarium_production/venv/lib/python3.6/site-packages',  '/home/scholarium/scholarium_staging/venv/lib/python36.zip',  '/home/scholarium/scholarium_staging/venv/lib/python3.6',  '/home/scholarium/scholarium_staging/venv/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/scholarium/scholarium_staging/venv/lib/python3.6/site-packages',  '/home/scholarium/scholarium_production/venv/lib/python3.6/site-packages/IPython/extensions',  '/var/www/.ipython']
Di, 12 Dez 2017 22:13:06 +0100

**Comment by rahim-t** [comment]
Trello ist noch nötig für die Erstellung der gedruckten Scholien - d.h. ein Umbau dieses Skripts erforderlich

**Comment by rahim-t** [comment]
Jetzt: Server Error (500)

**Comment by wmles** [comment]
Hallo Rahim,
ja, das solle auch so sein, ich hatte gestern nur vergessen, in den
settings.py das "debug=False" einzustellen, hatte es vorher zum
Verstehen des Fehlers am Vormittag auf "debug=True" gesetzt; ist mir
erst durch deine Mail aufgefallen.

Und die normalen user sollen ja keinen debug-output sehen, das macht
ja Angriffe möglich (es wird empfohlen, lieber zu schizophren zu sein,
"the internet is a hostile area").

...Übrigens ist das noch ein Argument für meine Präferenz, immer den
gleichen Code für production und staging ausgecheckt zu haben, dann
kann man jeden Fehler in der staging reproduzieren und sieht die
debug-Meldungen.

Melde mich morgen nochmal...
ilja

**Comment by MerlinB** [comment]
@wmles Ich nehme an, der Fehler hängt mit apache/nginx/wsgi zusammen, da er über die shell nicht auftritt. Ideen?

**Comment by MerlinB** [comment]
wenn ist ausführe:
`locale.getlocale(), locale.getdefaultlocale(), sys.getfilesystemencoding(), sys.getdefaultencoding()`
bekomme ich über die shell:
`('en_US', 'UTF-8'), ('en_US', 'UTF-8'), utf-8, utf-8`
Wenn das gleiche aber über einen Webzugriff ausgeührt wird bekommt man:
`(None, None), (None, None), ascii, utf-8`

**Comment by wmles** [comment]
ich hab jezt einiges rumprobiert und bekomme inzwischen Fehler, weil
pandoc nicht installiert ist - da ist es ja erstmal kein Wunder,
wenn's auf dem Server nicht läuft^^ ich versuche alle dependencies zu
installieren

**Comment by MerlinB** [comment]
Das kann nicht sein. Pandoc ist installiert und hat schon funktioniert auf dem Server.

**Comment by wmles** [comment]
Das ist ja lustig ...
ich hab sudo apt-get install pandoc eingegeben und der hat was gemacht.
Ich hab's leider vorher nicht probiert, aber jetzt geht pandoc über die bash.
jetzt fehlt ihm aber der filter pandoc-siteproc, da hänge ich grade...

**Comment by MerlinB** [comment]
Guck mal: https://github.com/valuehack/scholarium.at/tree/master/Workflow

**Comment by MerlinB** [comment]
https://stackoverflow.com/questions/47844627/django-unicodedecodeerror-only-on-apache-nginx

**Comment by MerlinB** [comment]
Bibliothek/aus_datei_einlesen geht übrigens auch nicht

**Comment by MerlinB** [comment]
Gelöst!
Die Lösung war in `/etc/apache2/envvars`:
```
## Uncomment the following line to use the system default locale instead:
. /etc/default/locale
```
Mit dem debian package aus https://github.com/jgm/pandoc/releases/tag/2.0.6 geht jetzt alles.
