### ISSUE TITLE
Mitwirkende (verlinkt in Footer & FAQ): Seite leer & weißer Bildrand unten

### ISSUE THREAD

**Issue by geraldk1** [valuehack/scholarium.at#86]

**Comment by MerlinB** [comment]
Danke, siehe Pull Request. Issue zur Seitenerstellung: https://github.com/valuehack/scholarium.at/issues/88

**Comment by MerlinB** [comment]
Links sind entfernt, weißer Rand https://github.com/valuehack/scholarium.at/issues/98
