### ISSUE TITLE
Weiterleitung bei alten urls

### ISSUE THREAD

**Issue by wmles** [valuehack/scholarium.at#9]
Urls mit GET-Daten (?id=blabla - vor allem relevant bei Scholien) weiterleiten auf die neue Struktur. 

Ist teilweise umgesetzt, also für Scholien. Bei einer Veranstaltung kommt man zum List-View. Das ist ganz okay, aber es wäre schöner, wenn dabei der get-Teil gestrippt wird und nicht nutzlos hinten dran hängen bleibt.

**Comment by MerlinB** [comment]
Für Scholien umgesetzt.
