### ISSUE TITLE
Tote Links in alten Scholienartikeln

### ISSUE THREAD

**Issue by MerlinB** [valuehack/scholarium.at#99]
Die Artikel verlinken untereinander, nutzer aber alte Links. z.B.: https://scholarium.at/scholien/index.php?q=[Artikel] statt https://scholarium.at/scholien/[Artikel]

**Comment by geraldk1** [comment]
Ich habe die Links jetzt schnell händisch in der DB ausgebessert (nach einer lokalen Admin-Suche nach "php") und zwar in folgenden Artikeln:

Ökonomik und Ethik des Crowdinvesting – eine kritische Analyse 
Marketing versus Produktion? – Die Dynamiken der Memufaktur 
Wettbewerb der Superlative 
Die Marktfeindlichkeit von K&uuml;nstlern 
Hochkonjunktur der Dummheit 
Namensgebung
Alpenphilosophie
Infantilisierung und Aggression an Universitäten (hier habe ich in der Slug das "ä" in "universitäten" zu einem "ae" umgewandelt - also die URL geändert. Ansonsten hätte sich der Eintrag nicht abspeichern lassen. Da auch der Link zum MOOC-Artikel fehlerhaft war und Umlaute in URLs von Webcrawlern schlechter erkannt werden, habe ich die URL dennoch geändert, was natürlich trotzdem nicht optimal ist.)

Damit sollte dieses Issue gelöst sein. Allerdings gibt es sicherlich noch externe Links zu Scholienartikeln, Scholienbüchlein, Veranstaltungen, Medien etc. (etwa auf Facebook oder in alten Newslettern), die "index.php" enthalten. Insofern wäre es gut, noch eine Weiterleitung über die *urls* oder direkt am Server zu implementieren. Siehe #100 

Außerdem ist mir im Zuge dessen aufgefallen, dass *slugify* Umlaute suboptimal umwandelt (aus *ü* wird *u* und nicht *ue* etc.) bzw. das *ß* einfach weglässt und nicht in *ss* umwandelt. Siehe #101
